/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author gabri
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
    }

    public JButton getButton_CloseProcessed() {
        return Button_CloseProcessed;
    }

    public JButton getButton_Processing() {
        return Button_Processing;
    }

    public JFrame getFrame_Processed() {
        return Frame_Processed;
    }

    public JTextArea getProcessed_TextArea() {
        return Processed_TextArea;
    }

    public JButton getButton_CloseHistory() {
        return Button_CloseHistory;
    }

    public JTextArea getHistory_TextArea() {
        return History_TextArea;
    }

    public JFrame getFrame_History() {
        return Frame_History;
    }

    public JButton getButton_Connect() {
        return Button_Connect;
    }

    public JButton getButton_Exit() {
        return Button_Exit;
    }

    public JButton getButton_History() {
        return Button_History;
    }

    public JButton getButton_Request() {
        return Button_Request;
    }

    public JTextField getIP_Text() {
        return IP_Text;
    }

    public JTextField getPR_Text() {
        return PR_Text;
    }

    public JTextField getRM_Text() {
        return RM_Text;
    }

    public JTextField getNI_Text() {
        return NI_Text;
    }

    public JTextField getPort_Text() {
        return Port_Text;
    }

    public JTextField getReplyPort_Text() {
        return ReplyPort_Text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_History = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        History_TextArea = new javax.swing.JTextArea();
        Button_CloseHistory = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Frame_Processed = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        Processed_TextArea = new javax.swing.JTextArea();
        Button_CloseProcessed = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IP_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Port_Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NI_Text = new javax.swing.JTextField();
        Button_Request = new javax.swing.JButton();
        Button_Exit = new javax.swing.JButton();
        Button_History = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RM_Text = new javax.swing.JTextField();
        PR_Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ReplyPort_Text = new javax.swing.JTextField();
        Button_Connect = new javax.swing.JButton();
        Button_Processing = new javax.swing.JButton();

        History_TextArea.setEditable(false);
        History_TextArea.setColumns(20);
        History_TextArea.setRows(5);
        jScrollPane2.setViewportView(History_TextArea);

        Button_CloseHistory.setText("Close");

        jLabel9.setText("History");

        javax.swing.GroupLayout Frame_HistoryLayout = new javax.swing.GroupLayout(Frame_History.getContentPane());
        Frame_History.getContentPane().setLayout(Frame_HistoryLayout);
        Frame_HistoryLayout.setHorizontalGroup(
            Frame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(Frame_HistoryLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Frame_HistoryLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Button_CloseHistory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Frame_HistoryLayout.setVerticalGroup(
            Frame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_CloseHistory)
                .addContainerGap())
        );

        Processed_TextArea.setEditable(false);
        Processed_TextArea.setColumns(20);
        Processed_TextArea.setRows(5);
        jScrollPane3.setViewportView(Processed_TextArea);

        Button_CloseProcessed.setText("Close");

        jLabel10.setText("Requests Processing");

        javax.swing.GroupLayout Frame_ProcessedLayout = new javax.swing.GroupLayout(Frame_Processed.getContentPane());
        Frame_Processed.getContentPane().setLayout(Frame_ProcessedLayout);
        Frame_ProcessedLayout.setHorizontalGroup(
            Frame_ProcessedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ProcessedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_ProcessedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(Frame_ProcessedLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Frame_ProcessedLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Button_CloseProcessed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Frame_ProcessedLayout.setVerticalGroup(
            Frame_ProcessedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ProcessedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_CloseProcessed)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client GUI");

        jLabel2.setText("Connection IP");

        IP_Text.setText("127.0.0.1");

        jLabel3.setText("Port");

        Port_Text.setText("80");

        jLabel4.setText("Number of Iterations");

        NI_Text.setText("1");

        Button_Request.setText("Request");

        Button_Exit.setText("Exit");
        Button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitActionPerformed(evt);
            }
        });

        Button_History.setText("History");

        jLabel5.setText("Requests Made");

        jLabel6.setText("Processed Requests");

        RM_Text.setEditable(false);
        RM_Text.setText("0");

        PR_Text.setEditable(false);
        PR_Text.setText("0");

        jLabel7.setText("Reply Port");

        ReplyPort_Text.setText("5002");

        Button_Connect.setText("Connect");

        Button_Processing.setText("Processing");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Connect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Request)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Processing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_History)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IP_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NI_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReplyPort_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Port_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(RM_Text)
                    .addComponent(PR_Text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IP_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Port_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Exit)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(RM_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(ReplyPort_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(PR_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(NI_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_History)
                            .addComponent(Button_Request)
                            .addComponent(Button_Connect)
                            .addComponent(Button_Processing))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Button_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CloseHistory;
    private javax.swing.JButton Button_CloseProcessed;
    private javax.swing.JButton Button_Connect;
    private javax.swing.JButton Button_Exit;
    private javax.swing.JButton Button_History;
    private javax.swing.JButton Button_Processing;
    private javax.swing.JButton Button_Request;
    private javax.swing.JFrame Frame_History;
    private javax.swing.JFrame Frame_Processed;
    private javax.swing.JTextArea History_TextArea;
    private javax.swing.JTextField IP_Text;
    private javax.swing.JTextField NI_Text;
    private javax.swing.JTextField PR_Text;
    private javax.swing.JTextField Port_Text;
    private javax.swing.JTextArea Processed_TextArea;
    private javax.swing.JTextField RM_Text;
    private javax.swing.JTextField ReplyPort_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
